rtl/src/ext_mem.v
software/bootloader/boot.c
system.mk

- Updated ext-mem in order to use the new way to access the cache CTRL (addr[MSB], in this case addr[DDR_ADDR_W] (one additional bit in the prefix for selection, i.e. a cache with input parameter 15, will use addr[15] in order to select the controller);
- small change in boot.c:  cache_init(FIRM_ADDR_W) to cache_init(DDR_ADDR_W). This would stop working when implementing MIG DDR4, since it will have DDR_ADDR_W = 30, while the firmware would be much smaller. Currently ext_mem.v is using caches with the size of DDR_ADDR_W, so incase it is the be implemented FIRM_ADDR_W, ext_mem will also require change.

ext_mem update; boot.c small change

---

software/console/console.c

Send 1 byte at a time from console to bootloader

Fix for transfering bigger firmwares

---

Makefile

fix remote simulator call: missing VCD flag; copy VCD file to the local PC

fix remote simulator call: missing VCD flag; copy VCD file to the local PC

---

hardware/src/ext_mem.v
software/bootloader/boot.c

- changed boot.c, this way can be sure everything was written to DDR, instead of just making sure L1-D wrote to L2.
- removed cache-related warnings during simulation

Small fixes for USE_DDR & RUN_DDR configuration

---

hardware/src/ext_mem.v

Mistakenly placed some wires inside a define (that wouldn't be used in USE_DDR=1 RUN_DDR=0).
Placed the code outside of the define.

small warning fix in ext_mem

---

hardware/include/cpu_tasks.v
software/firmware/Makefile
software/pc-emul/Makefile

Sending and receiving files as a request from the firmware is now available (simulation not supported yet).
The console now operates as a proxy for requests from the firmware (easy to add new types of requests if needed).

console now operates as a requests proxy

---

hardware/asic/README.md
hardware/asic/skywater/Makefile

Hi Sir,
This PR has changes for target for OpenLane flow. This target first starts the Docker container and then runs the flow for asic soc. 
Things to be addressed next include,
1. Inclusion of this Makefile into asic.mk .... hardware.mk.....system.mk flow so that system.mk should be able to call this Makefile. 
2. In this Makefile I am using example design from openlane for test only. For iob-soc I need to pass the VSRC and VHDR variables to the flow.tcl
regards

Added target for openlane flow

---

hardware/asic/README.md
hardware/asic/skywater/Makefile

Hi Sir,
I have made following changes in Makefile and now it is working with make asic. Complete flow of OpenLane is working.
1. " " with DOK_CMD were not required and were removed.
2. VSRC and VHDR never copied UART sw_reg.v which ws required by the yosys to synthesize. I manually copied it. So this must be  fixed.
3. For gen_if.v like files were only interface definition is defined like ( `INPUT ) yosys gives error [unexpected TOK_INPUT] and also in UART sw_reg.v which has definition like ( `SWREG)  yosys gives error [unexpected TOK_REG]. I replaced it with definition of the `SWREG from iob_lib. And after these changes yosys was able to compile the src.
4. PDK_ROOT that you specified is the default one. It is perfectly ok. But if you want to specify some other path for it, you can …

Changes made for OpenLane and now it is working

---

hardware/asic/skywater/Makefile
hardware/asic/skywater/build.sh
hardware/asic/skywater/config.tcl
hardware/asic/skywater/openram_config.py
hardware/asic/skywater/run_interactive.tcl

Hi,
Sir this PR has changes in Makefile plus other files added in order to place sram macro 
to wrapper black box. 
I have made changes to memakerwrap.py after discussion with Joao in order to add Skywater130 tech to 
it.
Now there are two issues in flow of OpenLane
1 What is the name of the top level module of iob-soc, since openlane requires this in order to synthesize the design. If I set it as "system" because of system.v as top level file it complains in iob_uart.v that no such module name as "system"
2 Even though I generate my wrapper (means wrapper of Skywater130) and add it to VSRC in Makefile. Yosys still compiles iob_tdp_ram.v why it still has this even though if I debug VSRC it does not have this file and iob_tdp_ram.v is not copied to the folder of "src" aswell
best regards

Targets for sram Macro placement

---

hardware/hardware.mk
hardware/simulation/simulation.mk

- Update submodules to latest master and devel commits
- Fix simulation by updating names of files read to generate `system.v` and `system.vh`:
- files are expected to have `.vh` extention instead of `.v` or `.sv`

Update submodules, fix simulation

---

hardware/asic/skywater/config.tcl

Hi
I just changed the target density in config.tcl. The value is changed to keep a balance in target density. If the target density is large we get the antenna violations and if too small we get routing congestion errors. 
Kindly, have a look.
regards

Just changed the target density in config.tcl

---

.gitmodules
config.mk
hardware/hardware.mk

- All submodules used for iob-soc are on `submodule`
- IOb-soc does not depend on submodules of submodules
- Note the exception for AXI module as they are "tied in together"
- Update variables `LIB_DIR` and `MEM_DIR`
- Add `AXI`, `MEM` and `LIB` submodules updated to latest master and or
devel commit
- Update CACHE to latest commit with same change to submodule
organization

add(submodules): Single level submodule dependency

---

config.mk

When running with RUN_EXTMEM=1, INIT_MEM should not be set to 0 automatically.

INIT_MEM=0 should be set manually

---

software/console/console

Instead of reading when the file is empty and then ignoring the byte if it is b''. Now it only reads the file when there is at least one byte in it.

Fixed bug that caused the verilator testbench to not pass the second test

---

hardware/fpga/fpga.mk

- Minor changes to fpga makefile fragment to support ethernet
integration:
- copy all generated logs from `CONSOLE_DIR` to `BOARD_DIR`
- copy all `*.log` files from `<REMOTE>/BOARD_DIR` to local
`BOARD_DIR`
- This is necessary, as the ethernet core generates two log files:
- one for the firmware/console output
- and another for the python scripts output

feat: changes to support ethernet core integration

---

hardware/fpga/fpga.mk

- concatenate each console TEST_LOG to the overall TEST_LOG
- delete console TEST_LOG before handling other console logs
- this removes possibility of overriding overall TEST_LOG in BOARD_DIR
with console TEST_LOG from a single unit test

fix(fpga): special handling of TEST_LOG

---

software/firmware/firmware.S

Without this fix, the cpu 'trap' signal would trigger when returning from the firmware's main function in a system with multiple peripherals.

Fix bug in firmware.S

---

Makefile
config.mk
document/presentation/presentation.tex
hardware/fpga/fpga.mk
hardware/fpga/quartus/CYCLONEV-GT-DK/verilog/top_system.v
hardware/fpga/quartus/DE10-LITE/verilog/top_system.v
hardware/fpga/vivado/AES-KU040-DB-G/verilog/top_system.v
hardware/fpga/vivado/BASYS3/verilog/top_system.v
hardware/hardware.mk
hardware/simulation/simulation.mk
hardware/simulation/verilog_tb/system_top_core.v
hardware/src/boot_ctr.v
hardware/src/int_mem.v
software/bootloader/boot.c
software/firmware/Makefile
software/firmware/firmware.c
software/pc-emul/Makefile
software/python/createSystem.py
software/python/createTestbench.py
software/python/createTopSystem.py
software/python/periphs_tmp.py
software/python/submodule_utils.py
software/software.mk

Replaced system build scripts previously in bash, by a python3 version
that allows for multiple instances of the same peripheral type (with
the same corename).
To add multiple instances of the same peripheral, add the corename of
that peripheral multiple times to the PERIPHERALS list in the config.mk
file.
For example, to have 2 UART instances, use the following PERIPHERALS list:
`PERIPHERALS ?=UART UART`
This list will create two instances named: UART0 and UART1
This new python3 based build process no longer uses the 'pio.vh' and
'inst.vh' files inside each peripheral. The signals from these files
are now taken directly from the port list of the verilog top module
for each peripheral.

Add multi-instance capability; Remove 'pio.vh' and 'inst.vh' file dependency.

---

hardware/simulation/icarus/Makefile
hardware/simulation/simulation.mk
hardware/simulation/verilator/Makefile
hardware/simulation/verilog_tb/system_core_tb.v
hardware/simulation/waves.gtkw
hardware/simulation/xcelium/Makefile

- rename module name from TOP to system_tb;
- update simulation Makefiles;
- change simulation.mk to avoid open .vcd file both on remote and local machines.

rename module name from TOP to system_tb

---

document/document.mk
hardware/fpga/fpga.mk
hardware/simulation/simulation.mk
software/pc-emul/Makefile

- Remove `-q` (quiet) flag from `diff` command that compares obtained
log with test.expected logs
- This prints the difference between the files to stdout

feat(diff): Print difference for test.expected

---

hardware/fpga/fpga.mk
hardware/fpga/quartus/CYCLONEV-GT-DK/test.expected
hardware/fpga/vivado/AES-KU040-DB-G/test.expected
hardware/simulation/simulation.mk
hardware/simulation/test.expected
software/firmware/firmware.c
software/pc-emul/Makefile
software/pc-emul/test.expected

- Update firmware to create test file:
1. firmware sends file to console
2. afterwards requests the file back
3. and compares with original sent file
- this avoids using `Makefile` as the transfered file
- using `Makefile` uses the local `Makefile` which is different for pc-emul, icarus, verilator, Cyclonev and AES-KU040.
- in particular for the icarus and verilator, using the `Makefile` as the transfered file generates different `test.log` outputs for    each simulator (icarus and verilog makefiles have different sizes). There we can't use the same expected file in `hardware/simulation/test.expected`.
- Update `test.expected` files

feat(sw): firmware creates transfered file

---

.gitignore
hardware/simulation/verilator/system_tb.cpp

In the verilator .cpp test-bench, the Timer function was changed. It now receives the time that is supposed to pass in ns instead of the number of half cycles. This allows for it to support multiple clk signals.

Enable support for multiple clk's in the verilator test-bench; Update gitignore file;

---

hardware/simulation/simulation.mk
software/python/submodule_utils.py

- Added python function to remove duplicates and parameters from peripherals list.
Use this python function instead of the 'sort' makefile function to get peripherals list without parameters and duplicates.
- Update PICORV32.

Fix bug parsing peripherals list.

---

.github/workflows/ci.yml

- Remove extra space before each line in verilator and icarus jobs

feat(ci.yml): fix ci.yml syntax

---

.github/workflows/ci.yml
Makefile
hardware/simulation/system_top.vt
hardware/src/ext_mem.v
hardware/src/int_mem.v
hardware/src/system.vt
iob_soc_setup.py

- Use nix-shell to run verilator target in ci.yml
- Add configurable main function. This is useful when this system is used as a submodule of another. This allows the main system to configure the setup process of this one.
- Update directories variable. `submodule_dirs` variable now uses uppercase names to match the peripheral corenames/types. Python functions use this dictionary to access the location of peripherals.
- Add python-cache-clean makefile target as dependecy of clean.
- Update submodules

feat(setup.py,ci.yml): use nix-shell in ci.yml; update iob_soc_setup.py

---

hardware/src/ext_mem.v
hardware/src/iob_soc.vt
iob_soc_setup.py

With RUN_EXTMEM=1 simulation blocks because the rvalid and ready signal are not correctly working with the iob-cache.
Now ios can have the `'is_defined':'SOMETHING'` key which creates and `ifdef SOMETHING ... endif` in the Verilog header automatically generated.

Simulation: progress in running simulation with RUN_EXTMEM=1;

---

hardware/fpga/quartus/CYCLONEV-GT-DK/iob_soc_fpga_wrapper.v
hardware/fpga/vivado/AES-KU040-DB-G/iob_soc_fpga_wrapper.v
hardware/simulation/src/iob_soc_top.vt
hardware/src/iob_soc.vt
iob_soc_setup.py
software/bootloader/iob_soc_boot.c

- Use correct `IOB_SOC_RUN_EXTMEM` macro in Verilog sources
- Remove temporary fix from iob_soc_boot.c as it is no longer required.
- Update PICORV32. It now includes a RUN_EXTMEM parameter.

Fix `IOB_SOC_RUN_EXTMEM` macro name

---

README.md
default.nix
hardware/simulation/src/iob_soc_tb.vt
hardware/simulation/src/iob_soc_top.vt
hardware/src/ext_mem.v
hardware/src/iob_soc.vt
iob_soc_setup.py

- Remove DCACHE_ADDR_W from iob_soc_setup.py as the new macro is set by the new LIB. This resolves https://github.com/IObundle/iob-soc/issues/529.
- Along with the new LIB, this resolves issue IObundle/iob-lib#430.
- Update README with instructions for usage of Nix environment.
- Add default.nix symlink to new shell.nix of new LIB.
- Update README according to new python-setup process.

Add default.nix; Update README; Resolve issues.

---

hardware/simulation/sim_build.mk
hardware/simulation/src/iob_soc_sim_wrapper.vt
software/sw_build.mk

- Add missing include.
- Rename pc-emul test to prevent overrides.
- Update LIB with new modifications to ssh connections and `board_client.py` version `V0.2`.
- Update `CONSOLE_CMD` variable from `sim_build.mk`.
The new LIB in this PR includes changes from PR: https://github.com/IObundle/iob-lib/pull/486

Update LIB and `CONSOLE_CMD`; Fix small bugs.

---

hardware/simulation/sim_build.mk
hardware/simulation/src/iob_soc_sim_wrapper.vt

- Remove unneeded `include iob_uart_swreg_def.vh` since it is auto-inserted by the python scripts during the setup process. This is a partial revert of commit eda4fa1.
- Update LIB

Remove unneeded file; Update LIB.

---

hardware/src/iob_soc.v
iob_soc.py
scripts/iob_soc_create_periphs_tmp.py
scripts/iob_soc_utils.py
software/src/iob_soc_firmware.S
software/src/iob_soc_firmware.c
software/src/iob_soc_system.h
software/src/python-setup/iob_soc_system.h
software/sw_build.mk
submodules/BOOT/hardware/src/iob_soc_boot.v
submodules/BOOT/iob_soc_boot.py
submodules/BOOT/software/src/iob_soc_boot.S
submodules/BOOT/software/src/iob_soc_boot.c
submodules/BOOT/software/src/iob_soc_preboot.S

List of changes:
- The project is compiling again (still with the python-setup files).
- More preparations were made to get the BOOT as a peripheral.
- The project is right now getting a string from the preboot rom (or the full rom, which begins with the preboot one) on the firmware stage.
- All peripheral and iob-soc *_conf.h files are now using the same format as put on LIB: begin with the peripheral name.
- Some BOOT macros removed from the top module and put instead on the peripheral files.
NOTE: compilation fixed for INIT_MEM=1 and USE_EXTMEM=1. I didn't test the other cases. This is one of the most important ones anyway. USE_EXTMEM=0 is not important (int_mem will be removed).

Compilation fixed again and more preparations

---

Makefile
iob_soc.py

New setup process no longer uses setup.mk or bootstrap.py The user calls `python3 -B ./iob_soc.py` directly to intiate the setup process (create the build dir).
Checkout the contents of the Makefile for examples.):

feat(setup): Use new setup process: Call `iob_soc.py` directly.

---

Makefile
README.md
hardware/src/iob_soc.v
hardware/src/iob_soc_boot_ctr.v
hardware/src/iob_soc_ext_mem.v
hardware/src/iob_soc_int_mem.v
hardware/src/iob_soc_sram.v
iob_soc.py
scripts/iob_soc_create_system.py
scripts/iob_soc_utils.py
submodules/LIB/scripts/iob_module.py
submodules/LIB/scripts/mkregs.py
submodules/LIB/scripts/verilog_tools.py
submodules/UART/hardware/src/iob_uart.v
submodules/UART/iob_uart.py

- Fix `ext_mem0` connections to `axi_m_port` bus.
- Fix regex expression in `iob_soc_create_system.py`.
- Update submodules with changes from LIB.
- Add support for `RW` register type in `mkregs.py`. 
- Rename `autologic` to `autoreg` in the fields of the `regs` dictionary.
- Add `_rd` and `_wr` suffixes to wires generated by `mkregs.py`, corresponding to the register type `R` or `W`, respectively.
- Rename generated `ready` signals (generated by `autoreg=False`) to end in either `_rready_rd` or `_wready_wr`.
Example `iob_uart_swreg_inst.vs` currently generated by `mkregs.py`:
```
wire [                                    1-1:0] SOFTRESET_wr;
wire [                                   16-1:0] DIV_wr;
wire [((UART_DATA_W > 1) ? UART_DATA_W : 1)-1:0] TXDATA_wdata_wr;
wire …
```

Fix `axi_m_port` interface; Fix iob_soc_create_system.py; Update submodules.

---

.github/workflows/ci.yml
submodules/LIB/Makefile
submodules/LIB/scripts/test.sh

- fix LIB module tests: update LIB modules test script to search for modules in `SOC/submodules`. This fixes failing tests with missing `axi_ram` found in `SOC/submodules/AXI`
- update SOC actions to run job testing LIB modules

feat(LIB): fix LIB module tests; add CI job

---

submodules/LIB/hardware/fpga/quartus/build.tcl
submodules/LIB/hardware/fpga/quartus/timing.tcl

- update quartus `build.tcl` to run `timing.tcl` once after static timing analysis
- improve clock domain specific setup and hold report names

fix(quartus): run `timing.tcl` once, report names

---

.github/workflows/ci.yml
submodules/LIB/hardware/fpga/Makefile

- add fpga test target. similar to simulation test target
- fpga-test checks for "Test passed" after regular fpga-run

feat(fpga): add fpga test target, update CI to run `fpga-test`

---

iob_soc.py
scripts/iob_soc_utils.py
submodules/LIB/scripts/submodule_utils.py

Update python scripts to give more flexibility to subclasses (OpenCryptoLinux):
- Allow subclasses to override the `N_SLAVES` and `N_SLAVES_W` macros;
- Update expression for the `axi_m_port` signals part select. The new expression also replaces code in the subclasses.

Allow override of `N_SLAVES` macro by subclasses; Update `axi_m_port` part select script. 

---

hardware/simulation/src/iob_soc_tb.cpp
software/src/iob_soc_boot.c
submodules/LIB/scripts/mkregs.py
submodules/UART/hardware/src/iob_uart.v

- update software macro addresses for software accessible registers to
have `_ADDR` sufix
- remove unused SWREG_rvalid_rd signal. Now swreg module generates
rvalid signal for all software accessible registers
- Addresses #618

fix(SWREG): <SWREG>_ADDR as macro address; remove unused <SWREG>_rvalikd_rd signal

---

scripts/iob_soc_create_periphs_tmp.py
scripts/iob_soc_utils.py
software/src/iob_soc_boot.S
software/src/iob_soc_boot.c
software/src/iob_soc_firmware.S
software/src/iob_soc_firmware.c
software/src/iob_soc_system.h
submodules/LIB/scripts/mk_configuration.py

Add a core name prefix to every macro in the generated `*_conf.h` file. This allows us to include this file in the system's firmware while avoiding duplicate macros from different cores.
Note: This PR may break drivers of cores that have not yet added the new prefix to their macros.
This resolves https://github.com/IObundle/iob-soc/issues/626

[BREAKING] Add core name prefix to `*_conf.h` macros.

---

submodules/LIB/hardware/modules/axil2iob/hardware/src/axil2iob.v

- axil2iob registers axil_bvalid_nxt as axil_bvalid_o

fix(axil2iob): register axil_bvalid_nxt

---

submodules/LIB/hardware/modules/iob_edge_detect/hardware/src/iob_edge_detect.v

- detected_o is used as wire in module, but declared as reg. Fixed
declaration
- declare and update detected_q in generate case when detected_q is used

fix(edge_detect)

---

software/sw_build.mk

- check USE_EXTMEM variable instead of just checking if variable exists. Fixes case where USE_EXTMEM=0 and firmware.hex is generated with MEM_ADDR_W size

fix(sw): check USE_EXTMEM variable

---

hardware/fpga/quartus/CYCLONEV-GT-DK/iob_soc_fpga_wrapper.v
hardware/fpga/vivado/AES-KU040-DB-G/iob_soc_fpga_wrapper.v
scripts/iob_soc_create_wrapper_files.py

PHY reset logic is now handled by the iob-eth core.

feat(ethernet): Remove PHY reset logic from wrappers.

---

submodules/LIB/setup.mk

modified a small line in setup.mk so when make setup is run the build directory has a copied version of caravel_project named caravel

modyfied something of the setupp.mk

---

hardware/simulation/src/iob_soc_sim_wrapper.v
hardware/simulation/src/iob_soc_tb.cpp
hardware/simulation/src/iob_soc_tb.v
hardware/src/iob_soc.v
hardware/src/iob_soc_boot_ctr.v
hardware/src/iob_soc_ext_mem.v
hardware/src/iob_soc_int_mem.v
hardware/src/iob_soc_sram.v
scripts/iob_soc_create_wrapper_files.py
submodules/LIB/hardware/modules/apb2iob/hardware/src/apb2iob.v
submodules/LIB/hardware/modules/axi2iob/hardware/src/axi2iob.v
submodules/LIB/hardware/modules/axil2iob/hardware/src/axil2iob.v
submodules/LIB/hardware/modules/axis2axi/hardware/simulation/src/axis2axi_tb.v
submodules/LIB/hardware/modules/axis2axi/hardware/src/axidelay.v
submodules/LIB/hardware/modules/iob2apb/hardware/src/iob2apb.v
submodules/LIB/hardware/modules/iob2axil/hardware/src/iob2axil.v
submodules/LIB/hardware/modules/iob_interface/iob_if_read.drom
submodules/LIB/hardware/modules/iob_iob2wishbone/hardware/src/iob_iob2wishbone.v
submodules/LIB/hardware/modules/iob_iobuf/hardware/src/iob_iobuf.v
submodules/LIB/hardware/modules/iob_merge/hardware/src/iob_merge.v
submodules/LIB/hardware/modules/iob_merge_v2/hardware/src/iob_merge2.v
submodules/LIB/hardware/modules/iob_split/hardware/src/iob_split.v
submodules/LIB/hardware/modules/iob_split_v2/hardware/src/iob_split2.v
submodules/LIB/hardware/modules/iob_tasks.vs
submodules/LIB/hardware/modules/iob_utils.vh
submodules/LIB/hardware/modules/iob_wishbone2iob/hardware/src/iob_wishbone2iob.v
submodules/LIB/scripts/if_gen.py
submodules/LIB/scripts/mkregs.py
submodules/LIB/scripts/submodule_utils.py
submodules/UART/hardware/src/iob_uart.v

- update CACHE submodule with test fixes
- update SOC and LIB hardware modules with missing `_i` and `_o` sufixes for input and output ports, respectively

fix(hw): add `_i` and `_o` sufixes to module ports

---

hardware/fpga/quartus/CYCLONEV-GT-DK/iob_soc_fpga_wrapper.v
hardware/simulation/src/iob_soc_sim_wrapper.v
iob_soc.py
scripts/iob_soc_create_wrapper_files.py

- update iob_soc_interconnect instance to use `clk_interconnect` and `arst_interconnect` 
- this allows to connect to clk and arst signals for CycloneV fpga and simulation wrappers 
- CycloneV has clk and arst - simulation has clk_i and arst_i
- fixes CycloneV with external memory

fix(soc_interconnect): custom clk arst signals

---

hardware/fpga/quartus/CYCLONEV-GT-DK/iob_soc_fpga_wrapper.v
submodules/LIB/hardware/modules/sync/iob_reset_sync/hardware/src/iob_reset_sync.v

- only declare clk_interconnect and arst_interconnect signals if Cyclonev is using external memory
- fix reset sync module: 
- declare sync as `wire` instead of `reg` 
- instantiate `iob_r` with correct `RST_VAL` in each `RST_POL` case

fix(fpga): cyclonev fpga wrapper, reset_sync

---

submodules/LIB/scripts/console.py
submodules/LIB/scripts/terminalMode.py

- renamed noncanonical.py to terminalMode.py for more clarity; if needed call terminalMode.py again when console finishes.

console (update):

---

hardware/fpga/vivado/iob_soc_fpga_wrapper_tool.sdc
submodules/LIB/hardware/modules/reg/iob_r/hardware/src/iob_r.v
submodules/LIB/hardware/modules/reg/iob_rn/hardware/src/iob_rn.v
submodules/LIB/hardware/modules/sync/iob_neg2posedge_sync/hardware/src/iob_neg2posedge_sync.v
submodules/LIB/hardware/modules/sync/iob_reset_sync/hardware/src/iob_reset_sync.v
submodules/LIB/hardware/modules/sync/iob_sync/hardware/src/iob_sync.v

- use distinct signal names for synchronizer registers. this enables using wildcard rules to identify synchronizer registers in fpga tools
- fix reg to wire
- update PICORV to avoid combinatorial loop

fix(hw): distinct signals for sync regs

---

submodules/LIB/scripts/console_ethernet.py
submodules/LIB/scripts/iob_module.py
submodules/UART/hardware/src/uart_core.v

Call `_auto_add_settings()` before `_copy_srcs()` in iob_module, to prevent auto added modules (like `iob_ctls`) from overriding top module files.

Fix module setup order; Only setup flows for top module.

---

submodules/LIB/hardware/modules/axis2axi/hardware/src/axis2axi_in.v

The `read_next` signal should only be asserted when there is a successful data transfer to the AXI interface.

Fix bug in `read_next` signal of `axis2axi_in` module

---

hardware/fpga/fpga_build.mk

By setting `IS_FPGA` before including `sw_build.mk`, we can use this variable in the `ifeq` statements of the `sw_build.mk` file.
Currently useful in iob-soc-opencryptolinux.

Reorder variable definitions of `fpga_build.mk` 

---

iob_soc.py
software/src/iob_soc_firmware.c
submodules/LIB/hardware/modules/iob_timer/hardware/simulation/src/timer_tb.v
submodules/LIB/hardware/modules/iob_timer/hardware/src/iob_timer.v
submodules/LIB/hardware/modules/iob_timer/hardware/src/timer_core.v
submodules/LIB/hardware/modules/iob_timer/iob_timer.py
submodules/LIB/hardware/modules/iob_timer/software/example_firmware.c
submodules/LIB/hardware/modules/iob_timer/software/src/iob-timer.c
submodules/LIB/hardware/modules/iob_timer/software/src/iob-timer.h
submodules/LIB/hardware/modules/iob_timer/software/src/iob_timer_swreg_pc_emul.c

- add iob_timer to LIB modules - usage example in `iob_timer/software/example_firmware.c`
- add timer to iob-soc system by default
- print execution time in firmware
- addresses https://github.com/IObundle/iob-soc/issues/706

feat(timer): add iob_timer as LIB module

---

hardware/fpga/fpga_build.mk
iob_soc.py
submodules/LIB/scripts/build_srcs.py
submodules/LIB/scripts/iob_module.py
submodules/LIB/scripts/mk_configuration.py

The new `is_system` attribute, when set, causes the copy/generation of software and related files during the setup process.
It also add the `IS_FPGA` makefile variable to the `config_build.mk` file of the build directory.
Related to discussion in https://github.com/IObundle/iob-soc/pull/727

feat(is_system): Add `is_system` attribute to `iob_module`

---

submodules/LIB/scripts/bootstrap.py

When init_top_module raised an error, the variable BUILD_DIR in LIB/setup.mk would be empty and the "rm -rf $(BUILD_DIR)" command in the clean rule would delete the entire project.
Adding a try catch and printing a non existent folder appears to be the simpler approach to fixing this problem.

Added a try catch around get_build_dir otherwise error could delete entire project

---

submodules/LIB/setup.mk

This prevents setup scripts from assuming the `$(BUILD_DIR)` is the current directory and deleting files in it.

fix(setup.mk): Exit with error when `get_build_dir` command fails.

---

submodules/LIB/hardware/modules/iob_timer/software/linux/drivers/iob_timer.c
submodules/LIB/scripts/iob_module.py

The copying implemented is very primitive and needs improvement, the copy is done in iob_modules.py , but for this moment is sufecient to to test the next steps, the next step is to copy the other mem_Wrapper in other branch, and switch the simulation and the fpga to use the mem_wrapper instead of the iob_soc.

created a new src_common, added an empty mem_wrapper just to test the copying

---

hardware/common_src/iob_soc_mwrap.v
hardware/src/iob_soc.v
hardware/src/iob_soc_boot_ctr.v
hardware/src/iob_soc_int_mem.v

Rom putted in the mem wrapper, wires and io were added to the required modules, and added a new parameter to the top called boot_hex(it already existed in other models) but is added as a parameter to the memwrapper.
simulations and fpga test were sucessefull

rom putted in the top with sucess

---

hardware/src/iob_soc_boot_ctr.v

made an bad error, this is a pr to revert the error

reset of the error

---

Makefile
hardware/simulation/src/iob_soc_sim_wrapper.v
lib/hardware/simulation/verilator.mk
lib/scripts/if_gen.py
lib/scripts/iob_soc_create_system.py
lib/scripts/iob_soc_create_wrapper_files.py
lib/scripts/iob_soc_peripherals.py
lib/scripts/iob_soc_utils.py
lib/software/Makefile
software/sw_build.mk

- update if_gen2 branch to run iob_soc simulation
- add missing `software/include` path for compilation (some .h files are generated in that folder)
- update BUILD_DIR path in top level makefile: now in `../CORE_VERSION/build` by default
- refactor if_gen.py to have functions to only generate verilog wire portmap strings - instead on only writting to file, we can pass the strings to other scripts
- fixes to peripheral portmaps - use correct sufix in port name - use custom peripheral_portmap, if exists
* * *
- fixing simulation to work on removing the REQ/RESP macros and leverate if_gen.py to generate wires and portmaps for iob native buses

fix(sim): fix iob-soc simulation

---

iob_soc.py

The diff shows a lot of changes, but most of it is just fixing indentation and adding the `self.` keyword.
I have only changed the `iob_soc.py` file.
**Main modification done by this PR:**
Remove dataclass. Use normal `__init__` method to build iob_soc, instead of using a dataclass. This gives us more flexibility for attribute manipulation when running the constructor.
For example, we will want to call functions like `create_wire` and `create_port` before assigning connections to the modules. So we might as well just do it in one go inside of the `__init__` method.
(We cannot call the `create_wire` function from the attribute definition section of a dataclass).
**Secondary PR:**
I have also made another PR https://github.com/arturum1/iob-soc/pull/4 to add the `create_*` methods.
I've made …

refactor(iob_soc.py): Remove dataclass

---

submodules/LIB/setup.mk

- improve `clean` target to remove all `[top_module]_V*` build directories. Previously only removes current version
- addresses: iobundle/iob-soc#830

fix(setup): clean [corename]_V* pattern

---

hardware/common_src/iob_soc_mwrap.v
hardware/syn/syn_build.tcl
submodules/LIB/hardware/syn/build.tcl
submodules/LIB/scripts/default.nix
submodules/LIB/scripts/iob_module.py
submodules/LIB/scripts/patches/yosys/abc-editline.patch
submodules/LIB/scripts/patches/yosys/fix-clang-build.patch
submodules/LIB/scripts/patches/yosys/plugin-search-dirs.patch
submodules/LIB/scripts/yosys-abc.nix
submodules/LIB/scripts/yosys.nix

Added Yosys (with Yosys-ABC), included Volare into Nix (an open PDK package manager), rectified a Verilog syntax error introduced by myself; a wire named "do" was used, which is a reserved name, so changed it to "doo." Also, modified the synthesis process to properly handle SDC files and deactivated latch errors if pico32.v is present in the sources. 
Yosys is an open-source framework for Verilog RTL synthesis. It takes Verilog code as input and produces a synthesized netlist as output, which can then be used for further downstream processing, such as placement and routing. Yosys supports a wide range of synthesis optimizations and transformations, allowing users to achieve efficient and optimized hardware designs.
Yosys-ABC is an extension of the Yosys synthesis framework, integrating …

added yosys-abc and volare,fix syntax error ,end synthesys with genus

---

hardware/common_src/iob_soc_mwrap.v

When the IOB SoC was instantiated inside the MemWrap, its IO ports were hardcoded. This caused issues with other cores that required the IOB SoC ports to be dynamic. A modification was implemented to address this. This pull request contains the necessary changes.

Changed from hardcoded to dinamic io inside memwrap.v related to iob-soc instance.

---

.github/workflows/ci.yml

- update checkout action to v4 to use node 20 and remove warning:
```
- Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

fix(CI): update checkout action to use node 20

---

lib/hardware/modules/fifo2axis/fifo2axis.py
lib/hardware/modules/fifo2axis/hardware/src/fifo2axis.v

- tlast automatically resets after `len` fifo reads
- this allows to sinal new frames without resetting the module
- modcnt starts at max value, so that after first enable, counter goes to 0 and aligns with frame data
- update fifo2axis.py

feat(fifo2axis): update fifo2axis module

---

lib/scripts/default.nix

This updates nix-shell to use Py2HWSW 0.7.7 corresponding to PR IObundle/py2hwsw#21

feat(nix): Update Py2HWSW version

---

Makefile
lib/scripts/default.nix

The new `:` separator correctly captures the value for `use_extmem` passed from Makefile.
See description of https://github.com/arturum1/py2hwsw/commit/f24f15cfa8b21f660b24a15af57423d0c501e041 for details.

Use new `py_params` argument separator `:`

---

.github/workflows/ci.yml
default.nix
submodules/LIB/default.nix
submodules/LIB/hardware/modules/fifo/iob_fifo_async/hardware/simulation/src/iob_fifo_async_tb.v
submodules/LIB/hardware/modules/iob_inv/hardware/src/iob_inv.v
submodules/LIB/scripts/default.nix

It seems that new versions of nix-shell treat symlinks differently than old versions.
New versions of nix-shell use the symlink directory as the root for relative paths. Unlike in old versions where the original file was the root of relative paths.
This commit replaces symlinks with Nix files using the `import` keyword. This should work on both old and new versions of nix-shell.
Resolves issue https://github.com/IObundle/iob-soc/issues/924

Use Nix import instead of symlink

---

hardware/fpga/quartus/CYCLONEV-GT-DK/iob_soc_cyclonev_wrapper/iob_soc_cyclonev_wrapper.py
iob_soc.py
lib/hardware/buses/iob_axistream_in/hardware/src/iob_axistream_in.v
lib/hardware/buses/iob_axistream_in/iob_axistream_in.py
lib/hardware/buses/iob_axistream_out/hardware/src/iob_axistream_out.v
lib/hardware/buses/iob_axistream_out/iob_axistream_out.py
lib/hardware/iob_regfileif/iob_regfileif.py
lib/scripts/default.nix
submodules/BOOTROM/hardware/src/iob_bootrom.v
submodules/BOOTROM/iob_bootrom.py
submodules/BOOTROM/software/src/iob_soc_preboot.S

bootrom.v has issues with new py2hwsw version. Old csrs_inst.vs no longer exists and new attempt at replacing it is broken.

Fix need for ADDR-4 on preboot.S

---

iob_soc.py
lib/hardware/clocks_resets/iob_nco/iob_nco.py
lib/hardware/iob_system/iob_system.py
lib/hardware/iob_system/scripts/iob_system_utils.py
lib/hardware/iob_timer/iob_timer.py
lib/hardware/iob_uart/iob_uart.py
lib/scripts/default.nix

- New `iob_soc.py` passes attributes to parent core (iob_system) via python parameters.
This allows iob_system scripts to automate features from iob_soc attributes (like peripheral cbus connections).
- Replace iob_system `is_peripheral` attribute by `peripheral_addr_w`.
- Update py2hwsw version to match the one from PR https://github.com/IObundle/py2hwsw/pull/50.

Pass `iob_soc` attributes via python parameters to `iob_system` parent. 

---

scripts/iob_soc_create_system.py
submodules/LIB/scripts/config_gen.py
submodules/LIB/scripts/csr_gen.py
submodules/LIB/scripts/ipxact_gen.py

Similar to https://github.com/IObundle/py2hwsw/pull/80

Add support for doc_only attribute in confs and swregs

---

.github/workflows/ci.yml
submodules/LIB/document/Makefile
submodules/LIB/document/tsrc/config.tex
submodules/LIB/scripts/if_gen.py

- fix documentation typos
- fix document signature:
- distinguish user guide from release
- add version tag
- remove master slave references from standard interface comments

fix(doc): fix typos, signature, master/slave

---

submodules/LIB/hardware/modules/counter/iob_counter_ld/hardware/src/iob_counter_ld.v
submodules/LIB/hardware/modules/counter/iob_modcnt/hardware/src/iob_modcnt.v
submodules/LIB/hardware/modules/div/iob_div_subshift/hardware/src/iob_div_subshift.v
submodules/LIB/hardware/modules/div/iob_div_subshift_signed/hardware/src/iob_div_subshift_signed.v
submodules/LIB/hardware/modules/fifo/iob_fifo_async/hardware/src/iob_fifo_async.v
submodules/LIB/hardware/modules/fifo/iob_fifo_sync/hardware/src/iob_fifo_sync.v
submodules/LIB/hardware/modules/reg/iob_reg_r/hardware/src/iob_reg_r.v
submodules/LIB/hardware/modules/reg/iob_reg_re/hardware/src/iob_reg_re.v
submodules/LIB/hardware/modules/regfile/iob_regfile_2p/hardware/src/iob_regfile_2p.v
submodules/LIB/hardware/modules/regfile/iob_regfile_at2p/hardware/src/iob_regfile_at2p.v
submodules/LIB/hardware/modules/regfile/iob_regfile_sp/hardware/src/iob_regfile_sp.v

- remove wire declaration and assignment in the same line
- wire declaration and assignment does not work for ASIC
- only updated for asrc modules
- there are other modules still need changes
- list problem instances with: `grep -rn wire | grep =`

fix(hw): rm wire declaration and assign

---

submodules/LIB/hardware/modules/acc/iob_acc/hardware/src/iob_acc.v
submodules/LIB/hardware/modules/acc/iob_acc_ld/hardware/src/iob_acc_ld.v
submodules/LIB/hardware/modules/counter/iob_modcnt/hardware/src/iob_modcnt.v

- update modules to improve coverage:
- accumulators now have `INCR_W` parameter to set increment width,
different from `DATA_W`
- update modcnt to remove internal `ld_val` always 0. Keep same
functionality

fix(coverage): update modules to improve coverage

---

submodules/LIB/hardware/modules/iob_prio_enc/hardware/src/iob_prio_enc.v

- update priority encoder to output W if input = 0.
- use internal wire with logic to make MSB = 1 if input = 0
- this construction yields no linter warnings

fix(prio_enc): null input case

---

default.nix

-  Fix python version of nix environment to match the one from py2hwsw.
Details in commit: [fix(nix): Use python version from py2hwsw](https://github.com/IObundle/iob-soc/commit/ae789900996fd70d42601dc19e20ec64f93db575)
Resolves https://github.com/IObundle/py2hwsw/issues/268
- Update py2hwsw version.

Use nix python version from py2hwsw; Update py2hwsw.

---

submodules/LIB/hardware/modules/iob_axil2iob/hardware/src/iob_axil2iob.v
submodules/LIB/hardware/modules/iob_axil2iob/iob_axil2iob.py
submodules/LIB/hardware/modules/iob_iob2axil/hardware/src/iob_iob2axil.v
submodules/LIB/hardware/modules/iob_iob2axil/iob_iob2axil.py

- update axil2iob module with fix from py2hwsw repository
- commits: 428a6cf2 and 4aec6e2a
- also update iob2axil for symmetry

fix(axil2iob, iob2axil): port modules from py2hwsw (pre rready removal)
