IObundle/iob-soc

rtl/testbench/system_tb.v
simulation/noboot_int.gtkw

- small change to system_tb.v
-added cache front-end signals in gtkwave window noboot.

testbench small-fix

---

fpga/synth.mk
fpga/xilinx/AES-KU040-DB-G/Makefile
rtl/src/src.mk
software/ld-sw/Makefile
software/ld-sw/console.c
system.mk

update ld-sw framework according to new implementations; improve ld-sw for run from a script; improve synth.mk; cleanup src.mk defines

---

software/system.h

BITS_TO_REPRESENT(N) now returns the same result as $clog2(N)

Fixed BITS_TO_REPRESENT

---

Makefile
hardware/hardware.mk

- Added 'clean-sim' target to 'clean' in Makefile.
- Added loop to include all .vh files to system.v.

Added support for any number of .vh files.

---

hardware/simulation/verilator/Makefile

Adding some of the initial changes with the flags

Verilator changes

---

.gitignore
hardware/simulation/simulation.mk
hardware/simulation/verilator/Makefile
hardware/testbench/sim_xtop.cpp
system_config.mk

Testbench with clk and reset signal seems to be working.

Verilator testbench seems to be working

---

hardware/testbench/sim_system_top.v

Just putting in this PR so that if things are not as desired you can comment and have a look at what's going on

Verilator updates to wrapper

---

hardware/fpga/CYCLONEV-GT-DK/Makefile
hardware/fpga/DE10-LITE/Makefile
hardware/fpga/DE10-LITE/top_system.sdc
hardware/fpga/DE10-LITE/top_system.tcl
system.mk

Updated DE10 to work with makefile revamp changes.

Makefile revamp working for DE10 FPGA

---

hardware/fpga/fpga.mk

fixed bug where sw changes would not build hw for init_mem=0;
fixed bug where make build was not forcing hw load;

Makefile revamp

---

README.md

Fixed typos
Added instructions to cache git credentials for a period of time

Added git password cache to README

---

hardware/asic/README.md

Hi Sir,
I have made changes in the README.md according to your comments. Kindly have a look. Also Makefile was perfect and for right now requires no more changes.
regards,
sharjeel

Made changes in README.md according to comments

---

hardware/fpga/quartus/CYCLONEV-GT-DK/test.expected
hardware/fpga/vivado/AES-KU040-DB-G/test.expected
hardware/simulation/icarus/test.expected
hardware/simulation/xcelium/test.expected

- Update test.expected files to pass `make test`

fix(test): Update test.expected files

---

document/document.mk

- fix `make test-doc-clean` target
- `make test-doc` passes test

fix(doc): Update documentation path

---

hardware/simulation/xcelium/test.expected
hardware/src/ext_mem.v

- Fix simulation, by updating instantiations of merge -> iob_merge and includes of interconnect.vh -> iob_intercon.vh from LIB
- update test.expected
- update UART submodule to latest devel branch

Fix simulation, update test.expected, update UART submodule

---

hardware/asic/asic.mk
hardware/asic/umc130/Makefile
hardware/fpga/fpga.mk
hardware/fpga/quartus/CYCLONEV-GT-DK/test.expected
hardware/fpga/vivado/AES-KU040-DB-G/test.expected
hardware/simulation/icarus/test.expected
hardware/simulation/simulation.mk
hardware/simulation/xcelium/test.expected

- `--force` option in `rsync` to delete non empty folders
- Update expected logs for `make test` target
- test.expected logs still need improvement

fix(test): Better cleanup of extra files, Update expected logs for test

---

config.mk
hardware/simulation/simulation.mk

- add missing `AXI_DIR` variable in `config.mk`
- remove `AXI_DIR` variable ovewrite in `simulation.mk`
- Update UART submoduel to latest devel branch commit

fix(AXI): Fix path to AXI submodule; Update UART

---

.gitignore
hardware/asic/skywater/Makefile
hardware/asic/skywater/config.tcl
hardware/asic/skywater/openram_config.py
hardware/asic/skywater/run_interactive.tcl

switched to devel for future work from now on

---

hardware/asic/skywater/Makefile
hardware/asic/skywater/config.tcl
hardware/asic/skywater/macro_placement.cfg

Hi
In order to resolve issues of OpenLane. Kindly do a  fresh clone from OpenLane  
git clone git@github.com:microSharjeel/OpenLane.git 
cd OpenLane/
make openlane                                                                                                                                                                                           
make pdk
make test
best regards

changes to remove output_log error from run_sta step

---

hardware/asic/skywater/Makefile

This change in path has solved this problem this complete path is requirement of the doclker, 
Please remove OPENLANE_HOME from bashrc since it is now in Makefile

change in OPENLANE_HOME path

---

hardware/simulation/verilator/system_tb.cpp
software/console/console

It still works as it did before. 
It writes one byte to the console and then waits until it was read to write the next one.
When a file is opened in write mode, with "w", it is automatically created and the old data is deleted.

Removed fseek and truncate from console and testbench.

---

software/console/console

The solution was, instead of asking to read file_size bytes on one request, make file_size*ser.read(1);

Fix ser.read(file_size) would not receive full s_fw.bin;

---

hardware/asic/umc130/Makefile

Name change of memakerwrap.py file to memwrapper.py

changes in umc130 Makefile

---

document/pb/test.expected

- Testing server gives different pb.aux file
- probably related to different pdflatex versions

feat(doc): update test.expected

---

hardware/hardware.mk
hardware/simulation/simulation.mk
software/bootloader/boot.c

- Update LIB and UART submodules
- LIB refactor replaced swreg.vh files for mkregs.conf files
- Update makefiles accordingly
- Update UART function calls

feat(LIB): update LIB, UART submodules

---

hardware/include/cpu_tasks.v
hardware/simulation/verilator/system_tb.cpp

- update LIB and UART submodule with latest mkregs addressing from cpu
- update cpu tasks accordingly: now ignore 2 least significant bits from
cpu address
- see IObundle/iob-lib#103

feat(mkregs): update LIB, UART, cpu tasks

---

.github/workflows/ci.yml

- update default shell to interactive. This sources `~/.bashrc`
- set jobs to run in sequence and always execute, even if a previous job
failed

feat(actions): update default shell

---

hardware/hardware.mk
info.mk

- update LIB, CACHE and UART submodules
- generate soc, cache and uart version.vh files
- fix setup problem when copying bootloaders sources to
`BUILD_DIR/sw/bsrc`

fix(setup): generate version files

---

hardware/fpga/quartus/DE5-NET/Makefile
hardware/fpga/quartus/DE5-NET/device.tcl
hardware/fpga/quartus/DE5-NET/qsys/QSysDE5QGen1x8If64.qsys
hardware/fpga/quartus/DE5-NET/top_system.sdc
hardware/fpga/quartus/DE5-NET/verilog/top_system.v
hardware/fpga/quartus/top_system.tcl

this is the early stage commit in order to have the first working state. there are some minor changes like using ifeqs and setting global assignments for some files which will be in the upcoming PRs.

The PCIE hard ip core implemented in the soc top_system and worked with riffa

---

hardware/fpga/quartus/CYCLONEV-GT-DK/verilog/top_system.v
hardware/fpga/vivado/AES-KU040-DB-G/verilog/top_system.v
hardware/simulation/verilog_tb/system_top_core.v
hardware/src/ext_mem.v
hardware/src/system_core.v

Had to add the `param AXI_LEN_W = 8;` to the simulation top file, fpga's top files, system_core and ext_mem Verilog modules.

Update LIB submodule to master HEAD;

---

config_setup.mk
hardware/hw_setup.mk
hardware/simulation/sim_setup.mk
iob_soc_setup.py

- Build dir generates successfully with `make setup`, however, the system does not compile in simulation.
- It fails simulation due to missing iob_intercon.vh from LIB. Need to
find alternative or modify Verilog code to not use it.
- Add sim and doc flows
- fpga flow currently has an issue
- Select fixed CACHE_CONFIG to 'iob'. This may need to change to 'axi'?
- Rename axi_gen.py to if_gen.py (according to new LIB)
- Add iob_soc_setup.py
- Update submodules

feat(build-lib): build dir generates successfully

---

hardware/simulation/iob_soc_top.vt
hardware/simulation/sim_build.mk
hardware/simulation/test.expected

- Fix wrong firmware name in parameter of axi_ram Verilog instance
- Add tests for RUN_EXTMEM and INIT_MEM
- Update test.expected
- Update submodules

Fix firmware name; Add tests for INIT_MEM and RUN_EXTMEM.

---

hardware/simulation/sim_build.mk
hardware/simulation/src/iob_soc_sim_wrapper.vt
hardware/simulation/src/iob_soc_tb.cpp
hardware/simulation/src/iob_soc_tb.vt
scripts/iob_soc.py
scripts/sim_wrapper.py

- Rename `iob_soc_top.vt` to `iob_soc_sim_wrapper.vt`
- Add mising `iob_lib.vh` include in `iob_soc_tb.vt`
- Update LIB

Rename `iob_soc_top.vt` to `iob_soc_sim_wrapper.vt`

---

Makefile
hardware/fpga/fpga.mk
hardware/simulation/verilator/Makefile

Updated UART submodule to point to latest master branch commit.
Updated LIB submodule to point to commit with board_client and board_server.
Fixed fpga.mk to use board_client.

fpga.mk: use board_client to check board availability.

---

iob_soc_setup.py

- update LIB submodule with format-check for python code
- format python code in repository
- format check runs during `setup` - if format-check fails, run `make format` and `make setup` again

feat(format): format python, update LIB

---

.clang-format
.github/workflows/ci.yml
hardware/simulation/src/iob_soc_tb.cpp
software/src/iob_soc_boot.c
software/src/iob_soc_firmware.c
software/src/iob_soc_system.h

- update LIB submodule
- add .clang-format configuration file to repository
- format C/C++ files

feat(format): update LIB. Add clang format

---

hardware/src/int_mem.v
hardware/src/iob_soc.v

This change allows to run simulation with QuestaSim.

*: added `include "iob_utils.vh" where necessary.

---

.github/workflows/ci.yml

- update CI to run individual fpga tests
- `fpga-test` target always runs 4 predefined fpga-tests

fix(CI): run individual fpga tests

---

submodules/LIB/hardware/fpga/Makefile
submodules/LIB/hardware/simulation/questa.mk

This PR fixes issue https://github.com/IObundle/iob-soc/issues/612.

Fix Simulation with QuestaSim; Fix constant board grab timeout on FPGA.

---

submodules/LIB/hardware/lint/alint.tcl
submodules/LIB/hardware/lint/spyglass.tcl
submodules/LIB/hardware/modules/axil2iob/hardware/src/axil2iob.v
submodules/LIB/hardware/modules/iob_edge_detect/hardware/src/iob_edge_detect.v
submodules/LIB/hardware/modules/iob_pulse_gen/hardware/src/iob_pulse_gen.v
submodules/LIB/scripts/mkregs.py

[pulse_gen] changed END (reserved) to FINISHED

[hw][mkregs] added missing parenthesis.

---

scripts/iob_soc_create_system.py

- Group signals with the same condition.

iob_soc_create_system.py (update):

---

submodules/LIB/hardware/fpga/Makefile
submodules/LIB/scripts/console.py

fpga/Makefile, console.py: pass GRAB_TIMEOUT value; call python3 instead of python.

---

hardware/caravel/src/iob_soc_test.v
submodules/LIB/scripts/caravel_setup.py
submodules/LIB/setup.mk

Basicly changed a line of IOB_module, added a library for function related to caravel, so after the build directory is made the caravel directory is made, the reason is so when the verilog files are copied, the have already a destination folder inside the caravel.

changed the way it copies

---

submodules/LIB/hardware/modules/apb2iob/hardware/src/apb2iob.v
submodules/LIB/hardware/modules/axil2iob/hardware/src/axil2iob.v
submodules/LIB/hardware/modules/axis2fifo/hardware/src/axis2fifo.v
submodules/LIB/hardware/modules/iob_timer/hardware/src/iob_timer.v
submodules/LIB/scripts/iob_module.py
submodules/LIB/scripts/mkregs.py
submodules/UART/hardware/src/iob_uart.v

[axis2fifo] registered axis_tready_o

[mkregs] csr-if converters are now automatically added to hw code

---

submodules/LIB/hardware/modules/apb2iob/hardware/src/apb2iob.v
submodules/LIB/hardware/modules/fifo/iob_bfifo/hardware/src/iob_bfifo.v
submodules/LIB/hardware/modules/iob_pack/hardware/src/iob_pack.v
submodules/LIB/hardware/modules/iob_unpack/hardware/src/iob_unpack.v
submodules/LIB/scripts/mkregs.py

[un/pack][bfifo] added missing parenthesis

[apb2iob] removed unused signals

---

hardware/caravel/src/iob_soc_test.v
submodules/LIB/scripts/caravel_copy.py
submodules/LIB/scripts/caravel_setup.py
submodules/LIB/setup.mk

Found the hold time problem, that was caused by a stupid mistake commited by me in the top file, basically the clock enable and the clock of the iob_counter were connected to the same pin, therefore creating problems related to the hold time in relation to the flip flops. Added a change that automatically changes the buffer synthetisis in the json file. added a python script that when make clean is performed, the top file of the caravel is copied again to the iob_soc/caravel/hardware/src directory.

Found hold time problem, fixed a parameter in the json file and added a copy funcionality

---

submodules/LIB/hardware/modules/fifo/iob_bfifo/hardware/src/iob_bfifo.v
submodules/LIB/hardware/modules/iob_pack/hardware/src/iob_pack.v
submodules/LIB/hardware/modules/iob_unpack/hardware/src/iob_unpack.v
submodules/LIB/scripts/iob_module.py

[bfifo] grouped all 2*DATA_W into localparam BUFFER_SIZE

[module,py] fixed adding version and generating conf_h when no swregs

---

hardware/src/iob_soc_sram.v

changed a line in iob_soc_sram, basicly commented a line

changed a line that is not connected to nothing

---

hardware/common_src/iob_soc_mwrap.v
hardware/src/iob_soc.v
hardware/src/iob_soc_boot_ctr.v
hardware/src/iob_soc_int_mem.v
hardware/src/iob_soc_sram.v

there was a dumb mistakes, but now its solved with sucess.

SPRAM passe with sucess

---

hardware/src/iob_soc_boot_ctr.v

Removed reg defenition and added iob_reg, there is a problem still.
when rom reg signals are switched to registers the iob_soc stops working still tryign to understand.

removed the sram reg defenition and switched to iob_reg

---

iob_soc.py
lib/scripts/iob_module.py
lib/scripts/iob_soc_utils.py

This is a draft PR discuss implementation details about merging the `_setup()` method into the `__init__()` method and about the use of python dataclasses.
Related to discussion in https://github.com/IObundle/iob-py2hw/pull/42
Initially I only modified the `iob_soc.py` and `iob_module.py` files.

Sketch for structure with dataclasses and merge `_setup()` into `__init__()`.

---

Makefile
hardware/src/iob_soc_int_mem.v

changed int_mem.v and the buildir top makefile.

xcellium fix 

---

lib/hardware/modules/iob_and/iob_and.py
lib/hardware/modules/iob_aoi/iob_aoi.py
lib/hardware/modules/iob_inv/iob_inv.py
lib/hardware/modules/iob_or/iob_or.py
lib/scripts/iob_module.py

Update `iob_aoi.py` and submodules

---

Makefile
lib/Makefile
lib/hardware/modules/fifo/iob_fifo_async/hardware/simulation/src/iob_fifo_async_tb.v
lib/hardware/modules/iob_nco/hardware/simulation/src/iob_nco_tb.v
lib/hardware/modules/iob_pulse_gen/iob_pulse_gen.py
lib/hardware/modules/iob_uart/iob_uart.py
lib/scripts/default.nix
lib/setup.mk

Github actions 'lib' test should now pass successfully.

Fix lib modules; Update py2hwsw version.

---

lib/hardware/modules/fifo/iob_bfifo/hardware/src/iob_bfifo.v
lib/hardware/modules/fifo/iob_bfifo/iob_bfifo.py
lib/hardware/modules/fifo/iob_fifo_async/hardware/simulation/src/iob_fifo_async_tb.v
lib/hardware/modules/fifo/iob_fifo_async/hardware/src/iob_fifo_async.v
lib/hardware/modules/fifo/iob_fifo_async/iob_fifo_async.py
lib/hardware/modules/fifo/iob_fifo_sync/hardware/simulation/src/iob_fifo_sync_tb.v
lib/hardware/modules/fifo/iob_fifo_sync/hardware/src/iob_fifo_sync.v
lib/hardware/modules/fifo/iob_fifo_sync/iob_fifo_sync.py
lib/hardware/modules/iob2axi/hardware/src/iob2axi.v
lib/hardware/modules/iob2axi/iob2axi.py
lib/hardware/modules/iob_asym_converter/hardware/src/iob_asym_converter.v
lib/hardware/modules/iob_asym_converter/iob_asym_converter.py
lib/hardware/modules/iob_clock/iob_clock.py
lib/hardware/modules/iob_functions/hardware/src/iob_functions.vs
lib/hardware/modules/iob_functions/iob_functions.py

I couldn't remove all macros though

Remove macros from some modules

---

lib/hardware/modules/axis_tasks/axis_tasks.py
lib/hardware/modules/axis_tasks/hardware/src/axis_tasks.vs

- add axis tasks for verilog simulation. follows iob_tasks pattern
- add module for multiplication using add shift method
- includes testbench similar to div sub shift

feat(lib): axis_tasks; mul add shift module

---

scripts/iob_soc_create_wrapper_files.py

- the script was connecting rstn to multiple output ports if we have multiple axi interconnect interfaces

fix(fpga): connect rstn wire to 1st interface

---

README.md
default.nix

Use py2 version from PR https://github.com/IObundle/py2hwsw/pull/62

Update py2 version; Add `README.md`.

---

default.nix

Update py2hwsw to support doc_only attribute in confs/csrs. Matches version from PR https://github.com/IObundle/py2hwsw/pull/80

Update py2hwsw version

---

default.nix
iob_soc.py

Related to https://github.com/IObundle/py2hwsw/pull/139

Update py2hwsw; Update peripheral attributes.

---

submodules/LIB/hardware/modules/fifo/iob_fifo_async/hardware/src/iob_fifo_async.v
submodules/LIB/hardware/modules/fifo/iob_fifo_async/iob_fifo_async.py
submodules/LIB/hardware/modules/fifo/iob_fifo_sync/hardware/simulation/src/iob_fifo_sync_tb.v
submodules/LIB/hardware/modules/fifo/iob_fifo_sync/hardware/src/iob_fifo_sync.v
submodules/LIB/hardware/modules/fifo/iob_fifo_sync/iob_fifo_sync.py
submodules/LIB/hardware/modules/iob2axi/hardware/src/iob2axi.v
submodules/LIB/hardware/modules/iob2axi/iob2axi.py
submodules/LIB/hardware/modules/iob_asym_converter/hardware/src/iob_asym_converter.v
submodules/LIB/hardware/modules/iob_asym_converter/iob_asym_converter.py
submodules/LIB/hardware/modules/iob_functions/iob_functions.py
submodules/LIB/hardware/modules/iob_functions/iob_functions.vh
submodules/LIB/scripts/csr_gen.py

- create iob_functions with IOB_MIN/IOB_MAX and other macros from utils
- replace `iob_utils` usage with `iob_function` header

fix(lib): iob_functions verilog header

---

hardware/fpga/fpga_build.mk
submodules/LIB/hardware/fpga/quartus/build.mk
submodules/LIB/hardware/fpga/quartus/build.tcl

- fix ku040 action for iob-soc
- update quartus constraints to use same structure of SDC files as vivado

fix(fpga, asic): fix ku040 action, quartus constraints

---

.github/workflows/ci.yml
Makefile
README.md
default.nix
hardware/fpga/fpga_build.mk
hardware/simulation/sim_build.mk
software/src/iob_soc_firmware.c
software/sw_build.mk

- Re-add `*_build.mk` files. Resolves https://github.com/IObundle/iob-soc/issues/977
- Update py2hwsw to use version from PR https://github.com/IObundle/py2hwsw/pull/144
- Update Makefile to support new `USE_INTMEM` parameter and add new `lint-run` target.
- Add board serial configuration instructions to README. Resolves IObundle#980

Resolve issues.

---

submodules/LIB/hardware/modules/div/iob_div_subshift/hardware/src/iob_div_subshift.v
submodules/LIB/hardware/modules/iob_fifo2axis/hardware/src/iob_fifo2axis.v

- update modules to remove spyglass warnings

fix(lint): lint fixes

---

submodules/LIB/hardware/modules/div/iob_div_subshift/hardware/src/iob_div_subshift.v
submodules/LIB/hardware/modules/iob_axil2iob/hardware/src/iob_axil2iob.v
submodules/LIB/hardware/modules/iob_fifo2axis/hardware/src/iob_fifo2axis.v
submodules/LIB/scripts/csr_gen.py

- revert changes to fifo2axis
- improve read race condition fix for div subshift
- update axil2iob module to remove unused aXprot signals from converter

fix(lint, axil2iob)

---

submodules/LIB/hardware/modules/div/iob_div_subshift/hardware/simulation/src/iob_div_subshift_tb.v
submodules/LIB/hardware/modules/div/iob_div_subshift/hardware/src/iob_div_subshift.v
submodules/LIB/hardware/modules/div/iob_div_subshift_frac/hardware/src/iob_div_subshift_frac.v
submodules/LIB/hardware/modules/iob_fp/iob_fp_div/hardware/src/iob_fp_div.v

- update div subshift module to have distinct dividend and divisor width
- this improves coverage
- update existing iob_div_subshift instances in iob-soc

fix(div): update div subshift

---

.github/workflows/ci.yml
Makefile
README.md
default.nix
hardware/fpga/fpga_build.mk
hardware/simulation/sim_build.mk
iob_soc.py
software/sw_build.mk

Uses py2hwsw version from PR: https://github.com/IObundle/py2hwsw/pull/191
Also add new `extra_pkgs` list in default.nix.

Update iob_soc according to new py2hwsw version

---

Makefile
default.nix
hardware/simulation/sim_build.mk
software/sw_build.mk

Updated py2hwsw to version of https://github.com/IObundle/py2hwsw/pull/231

Update iob-soc with latest py2hwsw

---

submodules/LIB/document/tsrc/config.tex
submodules/LIB/hardware/modules/iob_axistream/axistream_in/hardware/src/iob_axistream_in.v
submodules/LIB/scripts/config_gen.py
submodules/LIB/scripts/io_gen.py

[axistream_in] fixed int_tready
[config_gen] sorted conf_vh by type and added comments to separate

[io_gen] added note about inputs not being registered

---

.github/workflows/release-artifacts.yml
Makefile

- initial atempt to generate multiple build directories and upload them as build artifacts for repository releases
- addresses #1014

feat(gh): release artifacts

---

default.nix
submodules/LIB/default.nix

Same fix as the one applied in PR https://github.com/IObundle/iob-soc/pull/1019

fix(nix): Use same package versions as the ones in LIB/scripts/default.nix
